def rootProps = new Properties()
file("${rootDir.parentFile}/gradle.properties").withInputStream {
    rootProps.load(it)
}
rootProps.each { k, v ->
    if (!project.hasProperty(k)) {
        ext[k] = v
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation "io.github.green4j:green-jelly:0.1.6"
}
